<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-14 18:58:07                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class UserDAO extends AutoUserDAO
	{
		// your brilliant stuff goes here
		/**
		 * @return string
		 */
		public function getSequence()
		{
			return parent::getSequence() . '_seq';
		}

		/**
		 * @param $email
		 * @return User
		 * @throws Exception
		 * @throws ObjectNotFoundException
		 */
		public function getByEmail($email)
		{
			return Criteria::create($this)
				->add(Expression::eq('email', $email))
				->get();
		}

	}
?>