<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-12 23:00:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class WaitingRegistrationDAO extends AutoWaitingRegistrationDAO
	{
		// your brilliant stuff goes here

		/**
		 * @return string
		 */
		public function getSequence()
		{
			return parent::getSequence() . '_seq';
		}

		/**
		 * @param RegistrationRequest $registration
		 * @return WaitingRegistration
		 * @throws Exception
		 * @throws ObjectNotFoundException
		 */
		public function getWaitingByRegistrationRequest(RegistrationRequest $registration)
		{
			return Criteria::create($this)
				->add(Expression::eq('email', $registration->getEmail()))
				->get();
		}

		public function getByToken($token)
		{

			return Criteria::create($this)
				->add(Expression::eq('token', $token))
				->get();
				//->toString();
		}

	}
?>