<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:44:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoWaitingRegistration extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'WaitingRegistration', 8, true, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 128, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 256, true, true, false, null, null),
				'confirm' => LightMetaProperty::fill(new LightMetaProperty(), 'confirm', null, 'boolean', null, null, false, true, false, null, null),
				'registrationAt' => LightMetaProperty::fill(new LightMetaProperty(), 'registrationAt', 'registration_at', 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'confirmationAt' => LightMetaProperty::fill(new LightMetaProperty(), 'confirmationAt', 'confirmation_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
				'token' => LightMetaProperty::fill(new LightMetaProperty(), 'token', null, 'string', null, null, true, true, false, null, null),
				'queueEmail' => LightMetaProperty::fill(new LightMetaProperty(), 'queueEmail', 'queue_email', 'boolean', null, null, false, true, false, null, null)
			);
		}
	}
?>