<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:44:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBaseRequest extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'formName' => LightMetaProperty::fill(new LightMetaProperty(), 'formName', 'form_name', 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>