<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:44:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoSignInRequest extends ProtoBaseRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 128, true, true, false, null, null),
						'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 64, true, true, false, null, null)
					)
				);
		}
	}
?>