<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:44:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBaseRequest
	{
		protected $formName = null;
		
		public function getFormName()
		{
			return $this->formName;
		}
		
		/**
		 * @return BaseRequest
		**/
		public function setFormName($formName)
		{
			$this->formName = $formName;
			
			return $this;
		}
	}
?>