<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:44:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRegistrationRequest extends SignInRequest
	{
		protected $passwordConfirm = null;
		
		public function getPasswordConfirm()
		{
			return $this->passwordConfirm;
		}
		
		/**
		 * @return RegistrationRequest
		**/
		public function setPasswordConfirm($passwordConfirm)
		{
			$this->passwordConfirm = $passwordConfirm;
			
			return $this;
		}
	}
?>