<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:10:00                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class RegistrationRequest extends AutoRegistrationRequest implements Prototyped
	{
		/**
		 * @return RegistrationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoRegistrationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoRegistrationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>