<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-14 18:58:07                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class User extends AutoUser implements Prototyped, DAOConnected
{
    /**
     * @return User
     **/
    public static function create()
    {
        return new self;
    }

    /**
     * @return UserDAO
     **/
    public static function dao()
    {
        return Singleton::getInstance('UserDAO');
    }

    /**
     * @return ProtoUser
     **/
    public static function proto()
    {
        return Singleton::getInstance('ProtoUser');
    }


    public static function authUser(SignInRequest $request, HttpRequest $httpRequest)
    {
        $user = self::dao()->getByEmail($request->getEmail());

        if (!$user)
            return;

        if (password_verify($request->getPassword(), $user->getPassword())) {

            Cookie::create('profile_id')
                ->setValue($user->getId())
                ->httpSet();

            Cookie::create('token')
                ->setValue(
                    password_hash(md5($user->getPassword()), PASSWORD_DEFAULT)
                )
                ->httpSet();

            Session::assign('token', md5($user->getPassword()));
        } else {
            return;
        }
        return;
    }
}

?>