<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-12 23:00:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class WaitingRegistration extends AutoWaitingRegistration implements Prototyped, DAOConnected
	{
		/**
		 * @return WaitingRegistration
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return WaitingRegistrationDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('WaitingRegistrationDAO');
		}
		
		/**
		 * @return ProtoWaitingRegistration
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoWaitingRegistration');
		}

		public static function getWaitingByRegistrationRequest(RegistrationRequest $registration)
		{
			try{
				return self::dao()->getWaitingByRegistrationRequest($registration);
			}catch (ObjectNotFoundException $e)
			{
				return null;
			}
		}

		public static function getByToken($token)
		{
			try {
				self::dao()->getByToken($token);

			}catch (ObjectNotFoundException $e)
			{
				return null;
			}
		}
		
		// your brilliant stuff goes here
	}
?>