<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-10-15 21:44:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoWaitingRegistrationDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.waiting_registration';
		}
		
		public function getObjectName()
		{
			return 'WaitingRegistration';
		}
		
		public function getSequence()
		{
			return 'users.waiting_registration_id';
		}
	}
?>